// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"userId"`
	Uuid      pgtype.UUID        `json:"uuid"`
	IssuedAt  pgtype.Timestamptz `json:"issuedAt"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
	Revoked   bool               `json:"revoked"`
}

type Role struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type User struct {
	ID           int32              `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"passwordHash"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

type UserRole struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"userId"`
	RoleID    int32              `json:"roleId"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}
