services:
  db_dev:
    image: postgres:17.5-bookworm
    container_name: db_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_dev_data:/var/lib/postgresql/data

  db_test:
    image: postgres:17.5-bookworm
    container_name: db_test
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
    ports:
      - "${TEST_DB_PORT}:5432"
    volumes:
      - db_test_data:/var/lib/postgresql/data

volumes:
  db_dev_data:
  db_test_data:
