services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: development_db
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
  test-db:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: test_db
    volumes:
      - pgdata_test:/var/lib/postgresql/data
volumes:
  pgdata_dev:
  pgdata_test:
