import "@hotwired/turbo";
import { Application } from "@hotwired/stimulus";
import DateController from "./controllers/dateController";
import AmountController from "./controllers/amountController";
import FilterController from "./controllers/filterController";
import MacroSelectController from "./controllers/macroSelectController";
import NavController from "./controllers/navController";
import TaskFilterController from "./controllers/taskFilterController";
import SortController from "./controllers/sortController";
import ChartController from "./controllers/chartController";

window.Stimulus = Application.start();
window.Stimulus.register("date", DateController);
window.Stimulus.register("amount", AmountController);
window.Stimulus.register("filter", FilterController);
window.Stimulus.register("macro-select", MacroSelectController);
window.Stimulus.register("nav", NavController);
window.Stimulus.register("task-filter", TaskFilterController);
window.Stimulus.register("sort", SortController);
window.Stimulus.register("chart", ChartController);
